name: XEP validation

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Validate any XEP changes
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect changes to XEP files
        id: changed-xeps
        uses: tj-actions/changed-files@v41
        with:
          files: |
            xep-*.xml
            inbox/*

      - name: Validate changed file(s)
        if: steps.changed-xeps.outputs.any_changed == 'true'
        run: |
          sudo apt-get install -y libxml2-utils
          result=0
          for xep in "${{ steps.changed-xeps.outputs.all_changed_files }}"; do
            if ! tools/validate-xep0001-conformance.sh "$xep"; then
              result=1
            fi
            if [[ ${xep} == xep-* ]]; then
              echo Checking ${xep} by invoking \"make .${xep}.check.ok\"
              if ! make ".${xep}.check.ok"; then
                result=1
              fi
            fi
          done
          exit $result
